//
// Created by so on 18-04-2024.
//
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <sys/wait.h>
#include "monteCarlo.h"
#include "requisito_2.h"
#include "requisito_4.h"
#include <fcntl.h>

void requisito_2(char *filename, int num_processes, int total_points_generated) {

    //input file
    FILE *file = fopen(filename, "r");
    if (file == NULL) {
        printf("error opening file %s.\n", filename);
        return;
    }

    int n;
    fscanf(file, "%d", &n);

    Point *polygon = (Point *)malloc(n * sizeof(Point));
    if (polygon == NULL) {
        printf("error allocating memory\n");
        fclose(file);
        return;
    }

    for (int i = 0; i < n; i++) {
        fscanf(file, "%lf %lf", &polygon[i].x, &polygon[i].y);
    }

    fclose(file);

    // exit file
    int fd = open("results.txt", O_WRONLY | O_CREAT | O_TRUNC, S_IRUSR | S_IWUSR);
    if (fd == -1) {
        printf("error opening exit file\n");
        free(polygon);
        return;
    }

    int points_per_child = total_points_generated / num_processes;

    srand(time(NULL)); // seed

    Point *random_point = (Point *)malloc(total_points_generated * sizeof(Point));
    if (random_point == NULL) {
        printf("error allocating memory\n");
        free(polygon);
        close(fd);
        return;
    }

    // generate random points
    for (int i = 0; i < total_points_generated; i++) {
        random_point[i].x = ((double)rand() / RAND_MAX) * 2 - 1; //  -1 a 1
        random_point[i].y = ((double)rand() / RAND_MAX) * 2 - 1; //  -1 a 1
    }

    // child processes verify IsInside
    for (int i = 0; i < num_processes; i++) {
        int start = i * points_per_child;
        int end = start + points_per_child;
        pid_t pid = fork();
        if (pid < 0) {
            printf("fork failed\n");
            free(polygon);
            free(random_point);
            close(fd);
            return;
        } else if (pid == 0) {
            // child
            int points_inside_polygon = 0;
            for (int j = start; j < end; j++) {
                if (isInsidePolygon(polygon, n, random_point[j])) {
                    points_inside_polygon++;
                }
            }

            char buffer[100];
            int bytes_written = sprintf(buffer, "Process id:%d; Points generated by child: %d; Points inside polygon: %d;\n", getpid(), points_per_child, points_inside_polygon);
            write(fd, buffer, bytes_written);
            close(fd);
            free(polygon);
            free(random_point);
            exit(0);
        }
    }

    // wait for child processes closing
    for (int i = 0; i < num_processes; i++) {
        wait(NULL);
    }

    close(fd);
    free(polygon);
    free(random_point);

    printf("points written in results.txt.\n");
}

/*
void requisito_2(char *filename, int num_processes, int total_points_generated, Point polygon[], int n) {
    int fd = open(filename, O_WRONLY | O_CREAT | O_TRUNC, S_IRUSR | S_IWUSR);

    if (fd == -1) {
        printf("Erro ao abrir o ficheiro %s.\n", filename);
        return;
    }

    int points_per_child = total_points_generated / num_processes;
    srand(time(NULL)); // seed
    Point random_point[total_points_generated];

    for (int i = 0; i < total_points_generated; i++) {
        Point p;
        p.x = ((double) rand() / RAND_MAX) * 2 - 1; // Intervalo de -1 a 1
        p.y = ((double) rand() / RAND_MAX) * 2 - 1; // Intervalo de -1 a 1
        random_point[i] = p;
        //printf("%lf %lf\n", random_point[i].x, random_point[i].y);
    }
    for (int i = 0; i < num_processes; i++) {
        int inicio = i * points_per_child;
        int fim = inicio + points_per_child;
        pid_t pid = fork();
        if (pid < 0) {
            printf("Fork falhou.\n");
            return;

        } else if (pid == 0) {
            // Processo filho
            int points_inside_polygon = 0;
            for (int j = inicio; j < fim; j++) {

                if (isInsidePolygon(polygon, n, random_point[j])) {
                    points_inside_polygon++;
                }
                //printf(isInsidePolygon(polygon, n, random_point[j]) ? "Inside %lf %lf\n" : "Outside %lf %lf\n",random_point[j].x, random_point[j].y);

            }

            char buffer[100];
            int bytes_written = sprintf(buffer,
                                        "Process id:%d; Points generated by child: %d; Points inside polygon: %d;\n",
                                        getpid(), points_per_child, points_inside_polygon);
            write(fd, buffer, bytes_written);
            close(fd);
            exit(0);
        }
    }

    for (int i = 0; i < num_processes; i++) {
        wait(NULL);
    }

    close(fd);

    printf("Os pontos foram escritos em %s.\n", filename);
}*/