//
// Created by so on 18-04-2024.
//
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <sys/wait.h>
#include "monteCarlo.h"
#include "requisito_2.h"

void requisito_2(char *filename, int num_processes, int num_points_per_process, Point polygon[], int n) {
    FILE *file = fopen(filename, "w");
    if (file == NULL) {
        printf("Erro ao abrir o arquivo %s.\n", filename);
        return;
    }

    int points_per_child = num_points_per_process / num_processes;

    for (int i = 0; i < num_processes; i++) {
        pid_t pid = fork();
        if (pid < 0) {
            printf("Fork falhou.\n");
            return;
        } else if (pid == 0) {
            // Processo filho
            srand(time(NULL) ^ getpid()); // Semente diferente para cada processo filho

            int points_inside_polygon = 0;
            for (int j = 0; j < points_per_child; j++) {
                Point random_point = generateRandomPoint();

                if (isInsidePolygon(polygon, n, random_point)) {
                    points_inside_polygon++;
                }
            }

            fprintf(file, "Process id:%d; Points generated by child: %d; Points inside polygon: %d;\n", getpid(), points_per_child, points_inside_polygon);
            fclose(file);
            exit(0);
        }
    }

    // Processo pai espera por todos os filhos terminarem
    for (int i = 0; i < num_processes; i++) {
        wait(NULL);
    }

    fclose(file);

    printf("Os pontos foram escritos em %s.\n", filename);
}
