//
// Created by so on 18-04-2024.
//
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <sys/wait.h>
#include "monteCarlo.h"
#include "requisito_2.h"
#include "requisito_4.h"
#include <fcntl.h>


void requisito_2(char *filename, int num_processes, int total_points_generated, Point polygon[], int n) {
    int fd = open(filename, O_WRONLY | O_CREAT | O_TRUNC, S_IRUSR | S_IWUSR);

    if (fd == -1) {
        printf("Erro ao abrir o ficheiro %s.\n", filename);
        return;
    }

    int points_per_child = total_points_generated / num_processes;

    for (int i = 0; i < num_processes; i++) {
        pid_t pid = fork();
        if (pid < 0) {
            printf("Fork falhou.\n");
            return;
        } else if (pid == 0) {
            // Processo filho
            srand(time(NULL) ^ getpid()); // nova seed para cada processo filho

            int points_inside_polygon = 0;
            for (int j = 0; j < points_per_child; j++) {
                Point random_point = generateRandomPoint();

                if (isInsidePolygon(polygon, n, random_point)) {
                    points_inside_polygon++;
                }
            }

            char buffer[100];
            int bytes_written = sprintf(buffer, "Process id:%d; Points generated by child: %d; Points inside polygon: %d;\n", getpid(), points_per_child, points_inside_polygon);
            write(fd, buffer, bytes_written);
            close(fd);
            exit(0);
        }
    }

    for (int i = 0; i < num_processes; i++) {
        wait(NULL);
    }

    close(fd);

    printf("Os pontos foram escritos em %s.\n", filename);
}